### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by VigneshSP94** [cloudmarker/cloudmarker#78]
Is it possible to add usage documentation for this project? Like what this project for and what it does? It will be helpful to get an essence of what it does.

**Comment by susam** [comment]
Hi @VigneshSP94,

Thank you for creating this issue. Yes, we should add usage documentation for this project, so that any potential contributor or user can understand what this project is for, what it does, and how to configure and use it.

The current documentation is lacking in these details. I have created a new branch named `userdoc` and pull request for it (see #79) to address this issue. Visit https://github.com/cloudmarker/cloudmarker/blob/userdoc/README.rst to take a look at what the updated documentation would look like. This is still a work in progress. We are going to add a lot more details about this project in this branch in the next few days.

While we do this, you are also very welcome to contribute to the documentation in particular or the project in general if you wish to do so. If you have any questions about it, please do not hesitate to contact us by creating a [new issue](https://github.com/cloudmarker/cloudmarker/issues/new). Thank you, once again, for bringing our attention to the need for better documentation.
